name: MLOps-Assignment-3 CI/CD Pipeline

on:
  push:
    branches: docker_ci

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install the dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training script
      run: |
        python src/train.py

    - name: Verify model files exist
      run: |
        ls -la models/
        test -f models/linear_model.joblib
        test -f models/test_data.joblib

    - name: Build the Docker image
      run: |
        docker build -t californiahousinglinearregression:latest .

    - name: Test Docker container
      run: |
        docker run --rm californiahousinglinearregression:latest python src/predict.py

    - name: Login to Docker Hub platform
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      if: success()
      run: |
        docker tag assignment_3:latest ${{ secrets.DOCKER_USERNAME }}/californiahousinglinearregression:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/californiahousinglinearregression:latest
        echo "Docker image has been pushed successfully."
